import type { Metadata } from "next";
import FeatureLayout from "@/app/components/layout/FeatureLayout";
import FeaturePage, { type FeaturePageData } from "@/app/components/features/FeaturePage";

export const metadata: Metadata = {
  title: "Distribution — Distrozi",
  description: "Deliver your catalog to 150+ digital service providers globally. Maintain total independence and keep 100% of your royalties.",
};

const data: FeaturePageData = {
  badge: "Feature · Distribution",
  heroTitle: "Release Globally.",
  heroTitleHighlight: "Unrestricted Reach.",
  heroSubtitle:
    "Deliver your music to over 150 digital service providers and social platforms instantly. Maintain total independence and keep 100% of your earnings without sacrificing control.",
  accentClass: "text-[#008DFF]",
  glowColor: "rgba(0,141,255,0.12)",
  themeColor: "#004B8C", // Sleek dark blue for highlighted card
  showcaseImage: "/feature/distribution.png",
  showcaseAlt: "Music distribution platform interface",
  benefits: [
    {
      title: "150+ Platform Network",
      description:
        "Your music goes everywhere listeners are — landing securely on Spotify, Apple Music, YouTube Music, Amazon, TikTok, and over 140 regional stores.",
      image: "/features/benifit/4.png"
    },
    {
      title: "Zero Royalty Deductions",
      description:
        "We never touch your revenue streams. Every cent generated by your music flows directly to you without hidden fees or obscure backend percentages.",
      image: "/features/benifit/5.png"
    },
    {
      title: "Precision Rollout Control",
      description:
        "Launch globally simultaneously or target specific territories. Schedule releases months in advance and govern your exact pre-save strategy.",
      image: "/features/benifit/6.png"
    },
  ],
  sections: [
    {
      title: "Tailored DSP Architecture",
      description:
        "Define exactly how you distribute your releases. Choose between flexible direct DSP delivery agreements or leverage our established global ingestion network to build a distribution strategy that scales effortlessly with your imprint's growth.",
      image: "/features/8.png",
      imageAlt: "Digital Service Provider connections",
    },
    {
      title: "Worldwide Audience Reach",
      description:
        "Unlock massive global visibility. Transmit your audio to premier major streams, emerging regional ecosystems in Latin America and Asia, and modern lifestyle channels encompassing gaming hubs and integrated fitness applications.",
      image: "/features/9.png",
      imageAlt: "Global music footprint map",
    },
    {
      title: "Social Ecosystem Integration",
      description:
        "Capitalize immediately on viral moments. Transform background audio into primary revenue automatically across user-generated content platforms including TikTok, YouTube Shorts, Facebook, and Instagram Reels.",
      image: "/features/10.png",
      imageAlt: "Social media music monetization",
    },
    {
      title: "Automated Compliance Audits",
      description:
        "Bypass store rejections entirely. Our distribution engine enforces strict, automated metadata validation against each DSP's distinct structural rules, guaranteeing that your releases pass inspection flawlessly the first time.",
      image: "/features/11.png",
      imageAlt: "Distribution metadata quality control",
    },
    {
      title: "Strategic Delivery Windows",
      description:
        "Command ultimate authority over your launch timing. Trigger simultaneous global drops or curate staggered releases restricted by distinct timezones, ensuring the rollout flawlessly synchronizes with your PR and marketing campaigns.",
      image: "/features/12.png",
      imageAlt: "Music delivery scheduling and timing",
    },
    {
      title: "High-Volume Intake Processing",
      description:
        "Enterprise-level handling for expanding labels. Initiate, edit, or execute comprehensive takedowns across massive multi-artist catalogs simultaneously using centralized batch operations — preventing critical delays when minutes matter.",
      image: "/features/13.png",
      imageAlt: "Batch distribution and release pipeline",
    },
  ],
};

export default function DistributionPage() {
  return (
    <FeatureLayout>
      <FeaturePage data={data} currentHref="/features/distribution" />
    </FeatureLayout>
  );
}
